"""Initial migration: create venue table

Revision ID: 941306fd3310
Revises:
Create Date: 2026-01-10 14:02:25.219958

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "941306fd3310"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("website_url", sa.String(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("venue_type", sa.String(length=50), nullable=True),
        sa.Column("price_range", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("external_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "location", geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326), nullable=False
        ),
        sa.Column("scraper_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Create spatial index for location column using GIST
    op.execute("CREATE INDEX IF NOT EXISTS idx_venue_location ON venue USING gist (location)")
    op.create_index(op.f("ix_venue_active"), "venue", ["active"], unique=False)
    op.create_index(op.f("ix_venue_city"), "venue", ["city"], unique=False)
    op.create_index(op.f("ix_venue_last_scraped_at"), "venue", ["last_scraped_at"], unique=False)
    op.create_index(op.f("ix_venue_latitude"), "venue", ["latitude"], unique=False)
    op.create_index(op.f("ix_venue_longitude"), "venue", ["longitude"], unique=False)
    op.create_index(op.f("ix_venue_name"), "venue", ["name"], unique=False)
    op.create_index(op.f("ix_venue_source"), "venue", ["source"], unique=False)
    op.create_index(op.f("ix_venue_venue_type"), "venue", ["venue_type"], unique=False)
    op.create_index(op.f("ix_venue_website_url"), "venue", ["website_url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_venue_website_url"), table_name="venue")
    op.drop_index(op.f("ix_venue_venue_type"), table_name="venue")
    op.drop_index(op.f("ix_venue_source"), table_name="venue")
    op.drop_index(op.f("ix_venue_name"), table_name="venue")
    op.drop_index(op.f("ix_venue_longitude"), table_name="venue")
    op.drop_index(op.f("ix_venue_latitude"), table_name="venue")
    op.drop_index(op.f("ix_venue_last_scraped_at"), table_name="venue")
    op.drop_index(op.f("ix_venue_city"), table_name="venue")
    op.drop_index(op.f("ix_venue_active"), table_name="venue")
    op.drop_index("idx_venue_location", table_name="venue", postgresql_using="gist")
    op.drop_table("venue")
    # ### end Alembic commands ###
