"""Initial migration

Revision ID: e2ac96fa9e3e
Revises:
Create Date: 2026-01-10 15:46:28.196204

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2ac96fa9e3e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue",
        sa.Column("name", AutoString(length=255), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("website_url", AutoString(), nullable=False),
        sa.Column("city", AutoString(length=100), nullable=False),
        sa.Column("state", AutoString(length=50), nullable=True),
        sa.Column("country", AutoString(length=50), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("venue_type", AutoString(length=50), nullable=True),
        sa.Column("price_range", AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("external_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("scraper_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("source", AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Note: idx_venue_location is automatically created by GeoAlchemy2 when spatial_index=True
    op.create_index(op.f("ix_venue_active"), "venue", ["active"], unique=False)
    op.create_index(op.f("ix_venue_city"), "venue", ["city"], unique=False)
    op.create_index(op.f("ix_venue_last_scraped_at"), "venue", ["last_scraped_at"], unique=False)
    op.create_index(op.f("ix_venue_latitude"), "venue", ["latitude"], unique=False)
    op.create_index(op.f("ix_venue_longitude"), "venue", ["longitude"], unique=False)
    op.create_index(op.f("ix_venue_name"), "venue", ["name"], unique=False)
    op.create_index(op.f("ix_venue_source"), "venue", ["source"], unique=False)
    op.create_index(op.f("ix_venue_venue_type"), "venue", ["venue_type"], unique=False)
    op.create_index(op.f("ix_venue_website_url"), "venue", ["website_url"], unique=True)
    op.create_table(
        "event",
        sa.Column("name", AutoString(length=255), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_end_date"), "event", ["end_date"], unique=False)
    op.create_index(op.f("ix_event_name"), "event", ["name"], unique=False)
    op.create_index(op.f("ix_event_start_date"), "event", ["start_date"], unique=False)
    op.create_index(op.f("ix_event_venue_id"), "event", ["venue_id"], unique=False)
    # Note: spatial_ref_sys is a PostGIS system table and should not be dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: spatial_ref_sys is a PostGIS system table and should not be recreated here
    op.drop_index(op.f("ix_event_venue_id"), table_name="event")
    op.drop_index(op.f("ix_event_start_date"), table_name="event")
    op.drop_index(op.f("ix_event_name"), table_name="event")
    op.drop_index(op.f("ix_event_end_date"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_venue_website_url"), table_name="venue")
    op.drop_index(op.f("ix_venue_venue_type"), table_name="venue")
    op.drop_index(op.f("ix_venue_source"), table_name="venue")
    op.drop_index(op.f("ix_venue_name"), table_name="venue")
    op.drop_index(op.f("ix_venue_longitude"), table_name="venue")
    op.drop_index(op.f("ix_venue_latitude"), table_name="venue")
    op.drop_index(op.f("ix_venue_last_scraped_at"), table_name="venue")
    op.drop_index(op.f("ix_venue_city"), table_name="venue")
    op.drop_index(op.f("ix_venue_active"), table_name="venue")
    # Note: idx_venue_location is automatically dropped with the table by GeoAlchemy2
    op.drop_table("venue")
    # ### end Alembic commands ###
