"""Helper script to create a venue for testing."""

import asyncio
import sys

from cityvibe_core.database.connection import init_db
from cityvibe_core.database.session import get_session
from cityvibe_core.models.venue import Venue
from geoalchemy2 import WKTElement
from loguru import logger
from sqlalchemy import select


async def create_venue(website_url: str, name: str | None = None) -> str:
    """
    Create a venue in the database.

    Args:
        website_url: URL of the venue website to scrape
        name: Optional name for the venue (defaults to "Test Venue")

    Returns:
        The UUID of the created venue
    """
    init_db()

    async with get_session() as session:
        # Check if venue already exists
        result = await session.execute(select(Venue).where(Venue.website_url == website_url))  # type: ignore[arg-type]
        existing = result.scalar_one_or_none()

        if existing:
            logger.info(f"✅ Venue already exists: {existing.id} - {existing.name}")
            return str(existing.id)

        # Create a minimal venue (DebuikScraper will fill in the rest)
        # We need at least: name, website_url, latitude, longitude, location
        # Note: id is auto-generated by UUIDMixin
        venue = Venue(
            name=name or "Test Venue",
            website_url=website_url,
            city="Amsterdam",
            state="Noord-Holland",
            country="NL",
            latitude=52.3676,  # Amsterdam center (will be updated by scraper)
            longitude=4.9041,
            location=WKTElement("POINT(4.9041 52.3676)", srid=4326),
            source="debuik",
        )

        session.add(venue)
        await session.commit()

        logger.info(f"✅ Created venue: {venue.id} - {venue.name}")
        return str(venue.id)


async def list_venues() -> None:
    """List all venues in the database."""
    init_db()

    async with get_session() as session:
        result = await session.execute(select(Venue))
        venues = result.scalars().all()

        if not venues:
            logger.info("📭 No venues found in database")
            return

        logger.info(f"📊 Found {len(venues)} venues:")
        for venue in venues:
            logger.info(f"  - {venue.id}: {venue.name} ({venue.website_url})")


async def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python create_venue.py <website_url> [name]  # Create venue")
        print("  python create_venue.py --list                 # List venues")
        print()
        print("Example:")
        print('  python create_venue.py "https://www.debuik.nl/restaurant/123" "Restaurant Name"')
        sys.exit(1)

    if sys.argv[1] == "--list":
        await list_venues()
    else:
        website_url = sys.argv[1]
        name = sys.argv[2] if len(sys.argv) > 2 else None
        venue_id = await create_venue(website_url, name)
        print(f"\n✅ Venue ID: {venue_id}")
        print(f"   Use this ID to run: python test_task.py {venue_id}")


if __name__ == "__main__":
    asyncio.run(main())
